branch-defaults:
  master:
    environment: bookShop
    group_suffix: null
global:
  application_name: booksShop_universal
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
